USE bjkuzzoj0pxl0teng5am;

DROP TABLE IF EXISTS accounts;

CREATE TABLE accounts (
    ID INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASS VARCHAR(50) NOT NULL,
    DATE_CREATED DATE NOT NULL
) ENGINE=InnoDB;